#!/usr/bin/env python3
import json, os, sys
import matplotlib.pyplot as plt
import numpy as np


def load_json_data(file):
    with open(file, "r") as f:
        return json.load(f)


def set_plot(ax, config):
    ax.set_ylabel(config["y_axis_label"], labelpad=10, fontsize=14)
    if config["y_axis_logscale"]:
        ax.set_yscale("log")

    if config.get("y_axis_len", 0) > 0:
        ax.set_ylim([0, config["y_axis_len"]])

    ax.grid(True, linestyle="--", color="#D3D3D3", zorder=1)
    ax.tick_params(axis="both", length=0)

    if config["draw_continuous_x_axis"]:
        ax.set_xlabel(config["continuous_x_label"], labelpad=2, fontsize=14)
        ax.set_xticks([])
    else:
        x = range(len(config["x_label"]))
        ax.set_xticks(x)
        ax.set_xticklabels(
            config["x_label"],
            rotation=-90 if config.get("draw_vertical_x_axis_label", False) else 0,
            fontsize=14,
            ha="left",
        )

    if not config.get("draw_y_axis_value", True):
        ax.set_yticklabels([])

    # Plot each subplot
    for subplot in config["subplots"]:
        data = (
            [float(y) / subplot["normalize_to"] for y in subplot["data"]]
            if subplot["normalize_to"]
            else subplot["data"]
        )
        plot_zorder = 3
        if subplot["shape"] == "line" or subplot["shape"] == "line-vertex":
            ax.plot(
                range(len(data)),
                data,
                label=subplot["name"],
                color="#808080",
                zorder=plot_zorder,
            )
        elif subplot["shape"] == "bar":
            ax.bar(
                range(len(data)),
                data,
                label=subplot["name"],
                color="#808080",
                edgecolor="black",
                zorder=plot_zorder,
            )
        elif subplot["shape"] == "area":
            ax.fill_between(
                range(len(data)),
                0,
                data,
                label=subplot["name"],
                color="#808080",
                alpha=0.5,
                zorder=plot_zorder,
            )

        if subplot.get("draw_value", False):
            for i, datum in enumerate(data):
                ax.text(
                    i,
                    datum,
                    f"{datum:.2f}",
                    ha="center",
                    va="bottom",
                    zorder=plot_zorder,
                )

    if "title" in config:
        ax.set_title(config["title"], pad=10, fontsize=16)

    if config["draw_legend"]:
        ax.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.07),
            fancybox=True,
            shadow=True,
            ncol=3,
            fontsize=12,
        )


json_file = sys.argv[1]
configs = load_json_data(json_file)

# Creating a figure to contain all subplots
fig, axes = plt.subplots(1, len(configs), figsize=(8 * len(configs), 6))

if len(configs) == 1:
    axes = [axes]  # Make sure axes is iterable

for ax, config in zip(axes, configs):
    set_plot(ax, config)

fig.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.2, wspace=0.0125)
pdf_file = os.path.splitext(json_file)[0] + ".pdf"
plt.savefig(pdf_file, bbox_inches="tight")
plt.close()
